name: Commit Tests
on:
  push:

jobs:
  run-checks:
    name: run-checks
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: ci
    env:
      PUPPETEER_SKIP_DOWNLOAD: "true"
      VITE_FIREBASE_CONFIG_JSON: ${{ secrets.VITE_FIREBASE_CONFIG_JSON }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm run check
