name: GitHub Actions Demo
on: [push]

env:
  VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
  VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code for ${{ github.repository }}
        uses: actions/checkout@v3
      - name: Install nodejs
        uses: actions/setup-node@v3
      - name: Install node dependencies
        run: npm install
      - name: Run checks
        run: npm run check
      - run: echo "Done"
